version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: krs_online
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile-php
    container_name: backend_container
    restart: always
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    ports:
      - "9000:9000"

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile-php
    container_name: frontend_container
    restart: always
    working_dir: /var/www
    volumes:
      - ./frontend:/var/www
    depends_on:
      - backend
    ports:
      - "5173:5173"

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile-nginx
    container_name: nginx_container
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./backend:/var/www
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  mysql_data:
